import type { EditorThemeClasses } from "lexical";

const LexicalViewerTheme: EditorThemeClasses = {
  code: "LexicalViewerTheme__code",
  codeHighlight: {
    atrule: "LexicalViewerTheme__tokenAttr",
    attr: "LexicalViewerTheme__tokenAttr",
    boolean: "LexicalViewerTheme__tokenProperty",
    builtin: "LexicalViewerTheme__tokenSelector",
    cdata: "LexicalViewerTheme__tokenComment",
    char: "LexicalViewerTheme__tokenSelector",
    class: "LexicalViewerTheme__tokenFunction",
    "class-name": "LexicalViewerTheme__tokenFunction",
    comment: "LexicalViewerTheme__tokenComment",
    constant: "LexicalViewerTheme__tokenProperty",
    deleted: "LexicalViewerTheme__tokenDeleted",
    doctype: "LexicalViewerTheme__tokenComment",
    entity: "LexicalViewerTheme__tokenOperator",
    function: "LexicalViewerTheme__tokenFunction",
    important: "LexicalViewerTheme__tokenVariable",
    inserted: "LexicalViewerTheme__tokenInserted",
    keyword: "LexicalViewerTheme__tokenAttr",
    namespace: "LexicalViewerTheme__tokenVariable",
    number: "LexicalViewerTheme__tokenProperty",
    operator: "LexicalViewerTheme__tokenOperator",
    prolog: "LexicalViewerTheme__tokenComment",
    property: "LexicalViewerTheme__tokenProperty",
    punctuation: "LexicalViewerTheme__tokenPunctuation",
    regex: "LexicalViewerTheme__tokenVariable",
    selector: "LexicalViewerTheme__tokenSelector",
    string: "LexicalViewerTheme__tokenSelector",
    symbol: "LexicalViewerTheme__tokenProperty",
    tag: "LexicalViewerTheme__tokenProperty",
    unchanged: "LexicalViewerTheme__tokenUnchanged",
    url: "LexicalViewerTheme__tokenOperator",
    variable: "LexicalViewerTheme__tokenVariable",
  },
  embedBlock: {
    base: "LexicalViewerTheme__embedBlock",
    focus: "LexicalViewerTheme__embedBlockFocus",
  },
  hashtag: "LexicalViewerTheme__hashtag",
  heading: {
    h1: "LexicalViewerTheme__h1",
    h2: "LexicalViewerTheme__h2",
    h3: "LexicalViewerTheme__h3",
    h4: "LexicalViewerTheme__h4",
    h5: "LexicalViewerTheme__h5",
    h6: "LexicalViewerTheme__h6",
  },
  hr: "LexicalViewerTheme__hr",
  image: "editor-image",
  layoutContainer: "LexicalViewerTheme__layoutContainer",
  layoutItem: "LexicalViewerTheme__layoutItem",
  link: "LexicalViewerTheme__link",
  list: {
    checklist: "LexicalViewerTheme__checklist",
    listitem: "LexicalViewerTheme__listItem",
    listitemChecked: "LexicalViewerTheme__listItemChecked",
    listitemUnchecked: "LexicalViewerTheme__listItemUnchecked",
    nested: {
      listitem: "LexicalViewerTheme__nestedListItem",
    },
    olDepth: [
      "LexicalViewerTheme__ol1",
      "LexicalViewerTheme__ol2",
      "LexicalViewerTheme__ol3",
      "LexicalViewerTheme__ol4",
      "LexicalViewerTheme__ol5",
    ],
    ul: "LexicalViewerTheme__ul",
  },
  mark: "LexicalViewerTheme__mark",
  markOverlap: "LexicalViewerTheme__markOverlap",
  paragraph: "LexicalViewerTheme__paragraph",
  quote: "LexicalViewerTheme__quote",
  table: "LexicalViewerTheme__table",
  tableAddColumns: "LexicalViewerTheme__tableAddColumns",
  tableAddRows: "LexicalViewerTheme__tableAddRows",
  tableAlignment: {
    center: "LexicalViewerTheme__tableAlignmentCenter",
    right: "LexicalViewerTheme__tableAlignmentRight",
  },
  tableCell: "LexicalViewerTheme__tableCell",
  tableCellActionButton: "LexicalViewerTheme__tableCellActionButton",
  tableCellActionButtonContainer: "LexicalViewerTheme__tableCellActionButtonContainer",
  tableCellHeader: "LexicalViewerTheme__tableCellHeader",
  tableCellResizer: "LexicalViewerTheme__tableCellResizer",
  tableCellSelected: "LexicalViewerTheme__tableCellSelected",
  tableFrozenColumn: "LexicalViewerTheme__tableFrozenColumn",
  tableFrozenRow: "LexicalViewerTheme__tableFrozenRow",
  tableRowStriping: "LexicalViewerTheme__tableRowStriping",
  tableScrollableWrapper: "LexicalViewerTheme__tableScrollableWrapper",
  tableSelected: "LexicalViewerTheme__tableSelected",
  tableSelection: "LexicalViewerTheme__tableSelection",
  text: {
    bold: "LexicalViewerTheme__textBold",
    capitalize: "LexicalViewerTheme__textCapitalize",
    code: "LexicalViewerTheme__textCode",
    highlight: "LexicalViewerTheme__textHighlight",
    italic: "LexicalViewerTheme__textItalic",
    lowercase: "LexicalViewerTheme__textLowercase",
    strikethrough: "LexicalViewerTheme__textStrikethrough",
    subscript: "LexicalViewerTheme__textSubscript",
    superscript: "LexicalViewerTheme__textSuperscript",
    underline: "LexicalViewerTheme__textUnderline",
    underlineStrikethrough: "LexicalViewerTheme__textUnderlineStrikethrough",
    uppercase: "LexicalViewerTheme__textUppercase",
  },
};

export default LexicalViewerTheme;
